# Reto 1

In [1]:
import numpy as np

## Creación de arrays

### Crea dos arrays a partir de una lista

In [2]:
lista = [[5,8,3],[5,6,8]]

In [3]:
a1 = np.array(lista[0])
a1

array([5, 8, 3])

In [4]:
a2 = np.array(lista[1])
a2

array([5, 6, 8])

### Crea varios arrays de varias dimensiones

In [5]:
a3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a5 = np.array([[[1,2,3,4],[5,6,7,8]]])
a5

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [7]:
a52 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
a52

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

### Crea un array con tres columnas, cuatro filas

In [8]:
a4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a4

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### ¿Qué dimensión tendría el array de la pregunta 3?

In [9]:
a4.ndim #Dos dimensiones

2

## Funciones

### Crea una array de tres dimensiones con los mismos valores

In [10]:
a7 = np.full((1,3,3),6)
a7

array([[[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]]])

### Crea una array con un rango de 20 separados de manera equidistante

In [11]:
np.linspace(0,30,7) 

array([ 0.,  5., 10., 15., 20., 25., 30.])

### ¿Qué valor daría usar la función de identidad para una dimensión de 2?

In [12]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

### Si quiero crear un array con una separación de valores de dos en dos ¿qué función he de utilizar?

In [13]:
np.arange(0,10,2) 

array([0, 2, 4, 6, 8])

### Crea un array de con todos los valores en 0 de 4 dimensiones.

In [14]:
np.zeros((1,1,4,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

## Atributos

### Qué formula usarías para encontrar el tipo de datos y cuál sería para los siguientes:
#### a. [3,6,2]
#### b. [3.2,4.1,6.2]

In [15]:
a = [3,6,2]
b = [3.2,4.1,6.2]
#Por lo que veo son dos listas, ya sin hacer nada

In [16]:
type(a)

list

In [17]:
type(b)

list

### Que resultado da usar la formula shape una vez creado el array a partir de la preguna anterior(a y b)?

In [18]:
#Creamos el array
a1 = np.array([a,b])
a1

array([[3. , 6. , 2. ],
       [3.2, 4.1, 6.2]])

In [19]:
a1.shape

(2, 3)

### Qué tamaño tienen ambas

In [20]:
#No entiendo muy bien la pregunta, no se a que te refieres con ambas listas, o a ambos arrays que hemos creado
#la lista a tiene la siguiente dimensión
len(a)

3

In [21]:
#La lista b la siguiente
len(b)

3

In [22]:
#Y el array a1.
a1.ndim

2

### Convierte un array de dos y dimensiones en una dimensión

In [23]:
#Vamos a crear una lista vacía
lista = []
#Vamos a guardar en esa lista todos los elementos del array 1
for i in range(a1.shape[0]):
    for j in range(a1.shape[1]):
        lista.append(a1[i,j])
#Con esa lista, vamos crear otro array de otra dimensión
a2 = np.array(lista)
a2

array([3. , 6. , 2. , 3.2, 4.1, 6.2])

In [24]:
#Otra forma
np.reshape(a1,(6,)) #No olvidar las comas al ponerlo

array([3. , 6. , 2. , 3.2, 4.1, 6.2])

### Modifica el array anterior para convertirlo en uno de tres filas y dos columnas

In [25]:
np.reshape(a2,(3,2))

array([[3. , 6. ],
       [2. , 3.2],
       [4.1, 6.2]])

### Crea un array a partir de una lista del tipo de datos float, luego comprueba sus dimensiones.

In [26]:
lista2 = [[3.5,7.6, 1.2],[8.5,4.9,8.1]]
a3 = np.array([lista2[0],lista2[1]])
a3

array([[3.5, 7.6, 1.2],
       [8.5, 4.9, 8.1]])

In [27]:
a3.ndim

2

### Devuelve el número de elementos del array anterior.

In [28]:
a3.size

6

### Crea el siguiente array: [[4, 1, 6], [7, 1, 2]]. Como puedo puedo acceder al elemento con el numero 2?

In [29]:
a4 = np.array([[4, 1, 6], [7, 1, 2]])
a4
#Deberíamos especificar si s queremos el elemento dos de la primera fila o el de la segunda

array([[4, 1, 6],
       [7, 1, 2]])

In [30]:
#Elemento 2 de la primera fila
a4[0,1]

1

In [31]:
#Elemento 2 de la segunda fila
a4[1,1]

1

### Crea una matriz unidimensional de números secuenciales usando la sentencia arange entre 10 e incluyendo* 20 en incrementos (step) de 2. Luego use la sentencia reshape y shape para transformar esta matriz unidimensional en una matriz multidimensional de 2 elementos por 3 elementos. A continuación, la salida de la matriz multidimensional a la consola de Python utilizando una sentencia de impresión.
#### *20 debe incluirse; por eso se utiliza 21 dentro de la función arange().

In [32]:
#No entiendo muy bien si lo que quieres es que hagamos un array que comience en 10 y contenga los números de dos en dos hasta llegar al 21
a5 = np.arange(10,21,2)
a5

array([10, 12, 14, 16, 18, 20])

In [33]:
a5.shape

(6,)

In [34]:
np.reshape(a5,(2,3))

array([[10, 12, 14],
       [16, 18, 20]])

## Operaciones Matemáticas y filtros

### Crea un filtro que devuelva los valores mayores de 42 de tu propio array

In [35]:
#Creo un array cualquiera
arrandom = np.random.random((3,3))
arrandom

array([[0.10924691, 0.81535327, 0.1044049 ],
       [0.48165972, 0.50526846, 0.49509337],
       [0.47974683, 0.21955811, 0.66925745]])

In [36]:
#Multiplico cada valor por 100 para que me salgan valores mayores de 42
arrandom2 = arrandom * 100
arrandom2

#Se me ocurren tres maneras de resolver el problema

array([[10.92469145, 81.53532694, 10.44049027],
       [48.16597233, 50.52684575, 49.50933694],
       [47.97468306, 21.95581102, 66.92574461]])

In [53]:
arrandom[::-1]

array([[0.47974683, 0.21955811, 0.66925745],
       [0.48165972, 0.50526846, 0.49509337],
       [0.10924691, 0.81535327, 0.1044049 ]])

In [55]:
np.flip(arrandom)

array([[0.66925745, 0.21955811, 0.47974683],
       [0.49509337, 0.50526846, 0.48165972],
       [0.1044049 , 0.81535327, 0.10924691]])

In [37]:

#La primera haciendo un array de una dimensión que contenga sólo los números que sean mayores que 42
lista42 = []
for i in range(arrandom2.shape[0]):
    for j in range(arrandom2.shape[1]):
        if arrandom2[i,j] > 42:
            lista42.append(arrandom2[i,j])
arr421 = np.array(lista42)
arr421

array([81.53532694, 48.16597233, 50.52684575, 49.50933694, 47.97468306,
       66.92574461])

In [50]:
#Esta manera es más fácil, pero no recuerdo haberla visto en clase, por eso lo he realizado de la manera anterior
# Filtrar los valores mayores a 42
arr423 = arrandom2[arrandom2>42]
arr423

array([81.53532694, 48.16597233, 50.52684575, 49.50933694, 47.97468306,
       66.92574461])

In [39]:
#La segunda manera es creando un array de dos dimensiones que guarde los valores que sean mayores que 42
#En el mismo sitio donde estaban los valores originales y que muestre un 0 si el valor no es mayor de 42

#Creamos array vacio 
arr422 = np.empty(arrandom2.shape)

#En ese array guardamos los elementos mayores de 42 y luego le decimos que el resto de elementos sea cero
for i in range(arrandom2.shape[0]):
    for j in range(arrandom2.shape[1]):
        if arrandom2[i,j] > 42:
            arr422[i,j] = arrandom2[i,j]
        else:
            arr422[i,j] = 0
arr422


array([[ 0.        , 81.53532694,  0.        ],
       [48.16597233, 50.52684575, 49.50933694],
       [47.97468306,  0.        , 66.92574461]])

### Crea un filtro que devuelva solo los valores pares del siguiente array: arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [40]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
#Vamos a sacar el resto de dividir los valores del array entre 2
arr2 = arr % 2
arr2

array([1, 0, 1, 0, 1, 0, 1])

In [41]:
#Creamos una lista que guarde los valores par
lista = []
for i in range(arr2.shape[0]):
    if arr2[i] == 0:
        lista.append(arr[i])
#Creamos un array a partir de la lista de los pares
arrpares = np.array(lista)
arrpares

array([2, 4, 6])

In [42]:
#Hacemos el filtrado de manera fácil
arrpares2 = arr[(arr % 2) == 0]
arrpares2

array([2, 4, 6])

### Ahora para los impares del anterior array.

In [43]:
#Creamos una lista que guarde los valores impares
lista2 = []
for i in range(arr2.shape[0]):
    if arr2[i] != 0:
        lista2.append(arr[i])
print(lista2)

[1, 3, 5, 7]


In [44]:
#Hacemos el filtrado de manera fácil
arrimpares2 = arr[(arr % 2) != 0]
arrimpares2

array([1, 3, 5, 7])

### Encuentra el producto matricial de los siguientes arrays: test1 = np.array([[5, 2,3], [4, 8, 4]]) y test2 = np.array([[1, 1], [1, 6], [6, 3]])

In [45]:
test1 = np.array([[5, 2,3], [4, 8, 4]])
test2 = np.array([[1, 1], [1, 6], [6, 3]])
test3 = test1.dot(test2)
test3

array([[25, 26],
       [36, 64]])

### Eleva al cubo el siguiente array preg4 = np.array([[4, 5, 8],[2,8,5]])

In [46]:
preg4 = np.array([[4, 5, 8],[2,8,5]])
preg5 = preg4 ** 3
preg5

array([[ 64, 125, 512],
       [  8, 512, 125]])

### Encuentra a traspuesta de los arrays creados en el punto 1 y 4.

In [47]:
print(arr422.T)
#Le ponemos un parrafo que si no queda todo junto
print('\n')
print(test3.T)

[[ 0.         48.16597233 47.97468306]
 [81.53532694 50.52684575  0.        ]
 [ 0.         49.50933694 66.92574461]]


[[25 36]
 [26 64]]


### Suma la respuesta de la pregunta 5 a un nuevo array.

In [48]:
#Creamos un nuevo array
arrandom3 = (np.random.random((2,3)))*1000
arrandom3

array([[298.9915899 , 964.74192724,  50.80014334],
       [492.53303479, 852.38158636, 903.61687787]])

In [49]:
#Lo sumamos al de la pregunta 5
preg5 + arrandom3

array([[ 362.9915899 , 1089.74192724,  562.80014334],
       [ 500.53303479, 1364.38158636, 1028.61687787]])